### PR TITLE
Move to HCL2

### PR DESCRIPTION
**Pull request by splieth**
I changed to syntax in order to match the HCL2 spec.

### CODE REVIEW

**Review by mkirlin — APPROVED** [review]
This looks good to me. We ran into the same issue; would appreciate getting this merged. @raymondbutcher, thanks for your work building these modules!

**Comment by raymondbutcher** [comment]
Hi.

Sorry for the delay, I don't think I received any email about this.

I suppose the goal here is to make the module work with Terraform 0.12.x. To do that, we'll need to update the version of the Lambda module that this is using. So I'll merge this (thanks!) and then I'll get it ready for TF 12 and make a new release.

**Comment by raymondbutcher** [comment]
Hi @splieth @mkirlin I've released `v1.0.0` which I was able to apply using Terraform 0.12.12.

**Comment by mkirlin** [comment]
Awesome! Thank you so much for the quick response, and thanks again for all of the work you and the rest of the Claranet team have done on these modules.

**Pull request merged**
